// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProblemofmissingimageatproductsiteandunabletochangequantityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void problemofmissingimageatproductsiteandunabletochangequantity() {
    driver.get("https://skleptest.pl/");
    driver.manage().window().setSize(new Dimension(1920, 1032));
    driver.findElement(By.linkText("Black Top")).click();
    driver.findElement(By.cssSelector(".dashicons-plus")).click();
    driver.findElement(By.cssSelector(".dashicons-minus")).click();
    driver.findElement(By.name("add-to-cart")).click();
    driver.findElement(By.cssSelector(".top-cart")).click();
    driver.findElement(By.cssSelector(".top-cart > a")).click();
    driver.findElement(By.cssSelector(".dashicons-minus")).click();
    driver.findElement(By.cssSelector(".dashicons-minus")).click();
    driver.findElement(By.cssSelector(".dashicons-minus")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".dashicons-minus"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("update_cart")).click();
    {
      WebElement element = driver.findElement(By.name("update_cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
